variable "name" {
  description = "Name for the Boundary worker and related resources"
  type        = string
}

variable "instance_type" {
  description = "EC2 instance type for the Boundary worker"
  type        = string
  default     = "t3.medium"
}

variable "ami_id" {
  description = "ID of the custom AMI to use for the worker"
  type        = string
}

variable "subnet_id" {
  description = "ID of the subnet where the worker will be deployed"
  type        = string
}

variable "security_group_id" {
  description = "ID of the security group for the worker"
  type        = string
}

variable "ssh_key_name" {
  description = "Name of the SSH key pair for EC2 instance"
  type        = string
}

variable "controller_generated_token" {
  description = "Token for worker authentication generated by the controller"
  type        = string
  sensitive   = true
}

variable "boundary_version" {
  description = "Boundary version to install (include +ent suffix for enterprise)"
  type        = string
  default     = "0.15.0+ent"
}

variable "boundary_license" {
  description = "Contents of the Boundary Enterprise license"
  type        = string
  sensitive   = true
}

variable "common_tags" {
  description = "Common tags to apply to all resources"
  type        = map(string)
  default     = {}
}
